### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by niloomon**
Changes in 1) forming groups (Canvas instead of Google form), 2) Making the tournament optional and  baseline mandatory. 3) Grading policy

### CODE REVIEW

**Comment by eriq-augustine** [comment]
I think the real key thing here is that we see if we can standardize/normalize how we want P4 to be run each quarter.
(So that ideally we can draw from the same project/repo/file, and if not make standard instructions for each variant.)

@niloomon @lgilpin , should we meet up in summer to plan this out?
That would also be a great time to more formalize the tournament tools (especially if anyone has any spare ta/student/helper hours).

On the code side, I would remove the HTML comments and just make the changes directly.
(Since we can always consult git history to see older stuff and attribution.)

**Comment by niloomon** [comment]
Thanks for promptly commenting on this. The version I am making is temporary and won't be used in the future. This quarter since it was my first time teaching the course, I fell behind in the lectures and had to move deadlines by a week, so we are making the tournament optional. 
What is the best way to make such temporary changes? 
ALso, what is the difference between this repo  ("assignments") and "cse140-assignments"?

**Comment by eriq-augustine** [comment]
Okay, I see.

I am not 100% sure of the difference between the two repos (since I haven't been involved in the course logistics for a while),
but it looks like "assignments" is the public version of this repo.
This repo includes things like graders that we want to keep private, but it looks like that repo includes the instructions and resources students need (I assume copied from this repo).

So I would guess that for making a temporary/quarter-based change,
it would be best to change the files in that repo and then we can just toss out the changes for next quarter.

If time is an issue, I would just go ahead and directly make these changes in the "assignments" repo.
Then, @lgilpin can let us know if we did the right thing.

**Comment by niloomon** [comment]
Thanks Eriq. That makes sense, as I noticed the other folder contains more stuff.
I went ahead and made the changes in the original README. Students can see the new version now.
I t would be great to meet in summer to discuss the tournaments!

**Pull request merged**
